services:
  mongodb:
    image: mongo:7
    container_name: devops-compose-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./mern-project/server
    container_name: devops-compose-backend
    ports:
      - "5050:5050"
    environment:
      - ATLAS_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./mern-project/client
      args:
        REACT_APP_API_URL: http://localhost:5050
    container_name: devops-compose-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: