apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: host.docker.internal:5000/devops-backend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          env:
            - name: ATLAS_URI
              value: mongodb://mongodb:27017

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devops-case
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30050